#! /bin/bash

# Policy Docs
echo "vectorizing policy docs"
ctx_name="$1"
shift
python3 doc_crawler.py -cfg configs/*.yaml -t P -m en_core_web_sm -ctx $ctx_name "$@"

# Response Docs
echo "Fetching and vectorizing Responses"
python3 doc_crawler.py -cfg configs/*.yaml -t R -m en_core_web_sm -ctx $ctx_name "$@"
