study_leave:
  ids:
    - 12Un4Qt2RHlhfrXaFDOW3scMht8OOQc0RWr6O6cxHd80
  dir: ./poldocs/study_leave
  vector_dim:
    policy: 96
    response: 384
  templates:
    accepted: ./templates/study_leave/accepted.txt
    rejected: ./templates/study_leave/rejected.txt
    nmi: ./templates/study_leave/need_more_information.txt
  databases:
    policy: ./db/study_leave/policydb
    response: ./db/study_leave/responsedb
flexible_work:
  ids:
   - 1rTOROZgyIN0hXiXe9CdmWwDroxt5VcGGbH0KlKuCv_I
  dir: ./poldocs/flexible_work
  vector_dim:
    policy: 96
    response: 384
  templates:
    accepted: ./templates/flexible_work/accepted.txt
    rejected: ./templates/flexible_work/rejected.txt
    nmi: ./templates/flexible_work/need_more_information.txt
  databases:
    policy: ./db/flexible_work/policydb
    response: ./db/flexible_work/responsedb
